package com.myhitchhikingspots.model;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import com.crashlytics.android.Crashlytics;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 3): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 3;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        SpotDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        SpotDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(SpotDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Crashlytics.log(Log.INFO, "greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Crashlytics.log(Log.INFO, "greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + ".");

            switch (newVersion) {
                case 3: //Version created on November 06, 2016
                    execSQL(db, "ALTER TABLE " + SpotDao.TABLENAME + " ADD COLUMN '" + SpotDao.Properties.CountryCode.columnName + "' " + SpotDao.Properties.CountryCode.type.getSimpleName() + ";");
                    execSQL(db, "ALTER TABLE " + SpotDao.TABLENAME + " ADD COLUMN '" + SpotDao.Properties.HasAccuracy.columnName + "' " + SpotDao.Properties.HasAccuracy.type.getSimpleName() + ";");
                    execSQL(db, "ALTER TABLE " + SpotDao.TABLENAME + " ADD COLUMN '" + SpotDao.Properties.Accuracy.columnName + "' " + SpotDao.Properties.Accuracy.type.getSimpleName() + ";");
                    break;
                case 2:
                    execSQL(db, "ALTER TABLE " + SpotDao.TABLENAME + " ADD COLUMN '" + SpotDao.Properties.IsDestination.columnName + "' " + SpotDao.Properties.IsDestination.type.getSimpleName() + ";");
                    break;
                default:
                    dropAllTables(db, true);
                    onCreate(db);
                    Crashlytics.log(Log.INFO, "greenDAO", "All tables dropped.");
                    break;
            }
        }

        private void execSQL(Database db, String sql) {
            db.execSQL(sql);
            Crashlytics.log(Log.INFO, "greenDAO", sql);
        }
    }

}
