package com.myhitchhikingspots.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.myhitchhikingspots.model.Spot;

import com.myhitchhikingspots.model.SpotDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig spotDaoConfig;

    private final SpotDao spotDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        spotDaoConfig = daoConfigMap.get(SpotDao.class).clone();
        spotDaoConfig.initIdentityScope(type);

        spotDao = new SpotDao(spotDaoConfig, this);

        registerDao(Spot.class, spotDao);
    }
    
    public void clear() {
        spotDaoConfig.getIdentityScope().clear();
    }

    public SpotDao getSpotDao() {
        return spotDao;
    }

}
