package com.myhitchhikingspots.model;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.myhitchhikingspots.model.Spot;

import com.myhitchhikingspots.model.SpotDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig spotDaoConfig;

    private final SpotDao spotDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        spotDaoConfig = daoConfigMap.get(SpotDao.class).clone();
        spotDaoConfig.initIdentityScope(type);

        spotDao = new SpotDao(spotDaoConfig, this);

        registerDao(Spot.class, spotDao);
    }
    
    public void clear() {
        spotDaoConfig.clearIdentityScope();
    }

    public SpotDao getSpotDao() {
        return spotDao;
    }

}
